name: Tails
version: '1.0'
main: me.junioraww.tails.Main
api-version: '1.21'
commands:
  equip:
    description: Equip Owned Item
  items:
    description: Your Inventory
  spray:
    description: Graffiti!
  money:
    aliases: [ bal, me ]
  pay:
    aliases: [ transfer ]
    description: Pay to another player